name: nuri
version: 0.2.0
github: "suhdonghwi/nuri"
license: MIT
author: "Suh Donghwi"
maintainer: "hwidongsuh@gmail.com"
copyright: "2020 Suh Donghwi"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: 함수형 한글 프로그래밍 언어

dependencies:
  - base-noprelude >= 4.12
  - relude
  - megaparsec
  - parser-combinators
  - text
  - containers
  - mtl
  - transformers
  - lens
  - ordered-containers
  - binary
  - bytestring
  - pretty-simple
  # Since ghcide does not support multi cradle projects yet, these two dependencies have to be added here.
  # This is just temporary fix, and should be removed later.
  - hspec
  - hspec-megaparsec
  - neat-interpolation
  - directory
  - filepath
  - process
  - cmdargs

default-extensions:
  - OverloadedStrings
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - TemplateHaskell
  - TupleSections
  - QuasiQuotes
  - MultiWayIf
  - GADTs
  - ConstraintKinds

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  nuri:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wno-orphans
    dependencies:
      - nuri

tests:
  nuri-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wno-orphans
    dependencies:
      - nuri
      - hspec
      - hspec-megaparsec
      - neat-interpolation
